apiVersion: v1
kind: Service
metadata:
  name: http-service-1
  namespace: highlevel-prod
  labels:
    app: http-1
spec:
  selector:
    app: http-1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-deployment-1
  namespace: highlevel-prod
  labels:
    app: http-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: http-1
  template:
    metadata:
      labels:
        app: http-1
    spec:
      containers:
      - name: webpage
        image: kapilmodi/highlevel:1.0
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-lb-1
  namespace: highlevel-prod
spec:
  selector:
    app: http-1
  ports:
    - port: 80
      targetPort: 80
  externalTrafficPolicy: Local
  type: LoadBalancer
  